name: warpChest
main: net.ksm.mcp.Main
version: 1.2
author: K0SM0
description: This plugin is making list of warps of essentials, command /wc
depend: [Essentials]

commands:
  warpchest:
    description: Otwiera skrzynię z warpami
    usage: /warpchest
    aliases: [warpc, wc, wchest]