name: warpChest
main: net.ksm.mcp.Main
version: 1.0-SNAPSHOT
author: K0SM0
description: TODO
depend: [Essentials]

commands:
  warpchest:
    description: Otwiera skrzynię z warpami
    usage: /warpchest
    aliases: [warpc, wc, wchest]